// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrzQuJK2IVyp_l21WK_InOOuiixCNv1o',
    appId: '1:908998992312:web:789ee8b42c97d718af2f4d',
    messagingSenderId: '908998992312',
    projectId: 'kuizu-d00bd',
    authDomain: 'kuizu-d00bd.firebaseapp.com',
    storageBucket: 'kuizu-d00bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA423qfIO8b--luU3SLg83kj8Oa0I9bJ2M',
    appId: '1:908998992312:android:39a246cb505c0582af2f4d',
    messagingSenderId: '908998992312',
    projectId: 'kuizu-d00bd',
    storageBucket: 'kuizu-d00bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxN8hqnK5W9CbeDexwtTr1Xk-mlZyvFVg',
    appId: '1:908998992312:ios:06550c543564f42aaf2f4d',
    messagingSenderId: '908998992312',
    projectId: 'kuizu-d00bd',
    storageBucket: 'kuizu-d00bd.appspot.com',
    androidClientId: '908998992312-bvclcdurptbt64m21nikfi0vb7e6msmm.apps.googleusercontent.com',
    iosClientId: '908998992312-msf5eoh0oh3d3fate04hcp22jg7lvrm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuizu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxN8hqnK5W9CbeDexwtTr1Xk-mlZyvFVg',
    appId: '1:908998992312:ios:06550c543564f42aaf2f4d',
    messagingSenderId: '908998992312',
    projectId: 'kuizu-d00bd',
    storageBucket: 'kuizu-d00bd.appspot.com',
    androidClientId: '908998992312-bvclcdurptbt64m21nikfi0vb7e6msmm.apps.googleusercontent.com',
    iosClientId: '908998992312-msf5eoh0oh3d3fate04hcp22jg7lvrm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuizu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUrzQuJK2IVyp_l21WK_InOOuiixCNv1o',
    appId: '1:908998992312:web:fd6d97d01c98f091af2f4d',
    messagingSenderId: '908998992312',
    projectId: 'kuizu-d00bd',
    authDomain: 'kuizu-d00bd.firebaseapp.com',
    storageBucket: 'kuizu-d00bd.appspot.com',
  );

}